### ISSUE TITLE
xxHash is cousing some problems when used on non linux machines

### ISSUE THREAD

**Issue by Tarjei400** [Epimodev/svg-sprite-html-webpack#5]
With this ticket I wanted rather to elaborate on a problem we encountered. So on some machines, when installing project there are a lot of problems building packages using node-gyp, and it appeared with having this plugin as a dependency, in particular xxHash. My colleague made a quick research, and maybe we could change xxHash with xxHashjs, I will make a test pr. It will probably result in slightly slower sprite map generation, but this will mitigate problems with node-gyp

**Comment by Epimodev** [comment]
Yes I've also got some problems with node-gyp to build some projects in docker images. I've solve that by using a debian image instead of an alpine one (because I didn't find exactly what package to install to solve that).

Initially I choose xxHash because it was the fastest hash function I found.
But when I see it has dependencies which can lead to problems for installation I think it will be better to replace it.

I've check xxHashjs, it looks very nice. If you have time to make a PR which replace xxHash by xxHashjs, you can do it and I'll merge it very quickly.
Otherwise I can make this change tomorrow.

**Comment by Tarjei400** [comment]
Okay I made a quick test with xxHahsjs, in our use case I cant really feel the time difference :)

**Comment by Epimodev** [comment]
Ok perfect 👍
Even if it's a little slower, I think it will be insignificant compared to the rest of build process.

Thanks a lot :-)

**Comment by Tarjei400** [comment]
My pleasure :)

**Comment by Epimodev** [comment]
I just publish on npm version 2.1.2 with your PR
